### ISSUE TITLE
"accessed offsets" plots don't plot

### ISSUE THREAD

**Issue by roblatham00** [wangvsa/recorder-viz#2]
I get a little Bokeh icon for graphs 3.2 and 3.3 when I try to view my simple IOR trace..  I also get an empty 3.4:  Here's a screen shot of my browser's console log. I also pasted the error messages 

![image](https://user-images.githubusercontent.com/2278417/189748413-d47a2ed2-de5b-4ae5-8833-2dff41d3b3d9.png)

```
[bokeh] document idle at 27 ms
2bokeh-2.4.3.min.js:165 [bokeh] document idle at 8 ms
bokeh-2.4.3.min.js:165 [bokeh] document idle at 7 ms
3bokeh-2.4.3.min.js:521 
        
       [bokeh] could not set initial ranges
compute_initial @ bokeh-2.4.3.min.js:521
bokeh-2.4.3.min.js:165 [bokeh] document idle at 9 ms
bokeh-2.4.3.min.js:165 [bokeh] document idle at 4 ms
bokeh-2.4.3.min.js:165 [bokeh] document idle at 2 ms
bokeh-2.4.3.min.js:228 
        
       [bokeh] could not determine minimum data value for log axis, DataRange1d using value 0.1
_compute_range @ bokeh-2.4.3.min.js:228
bokeh-2.4.3.min.js:228 
        
       [bokeh] could not determine maximum data value for log axis, DataRange1d using value 10
_compute_range @ bokeh-2.4.3.min.js:228
bokeh-2.4.3.min.js:228 
        
       [bokeh] could not determine minimum data value for log axis, DataRange1d using value 0.1
_compute_range @ bokeh-2.4.3.min.js:228
bokeh-2.4.3.min.js:228 
        
       [bokeh] could not determine maximum data value for log axis, DataRange1d using value 10
_compute_range @ bokeh-2.4.3.min.js:228
2bokeh-2.4.3.min.js:285 
        
       Uncaught (in promise) TypeError: this.text.split is not a function
    at x.paint (bokeh-2.4.3.min.js:285:4491)
    at v._v_canvas_text (bokeh-2.4.3.min.js:386:1677)
    at v.paint (bokeh-2.4.3.min.js:386:1206)
    at v._render (bokeh-2.4.3.min.js:234:1007)
    at v.render (bokeh-2.4.3.min.js:206:1562)
    at O._paint_levels (bokeh-2.4.3.min.js:519:11560)
    at O._actual_paint (bokeh-2.4.3.min.js:519:10937)
    at O.paint (bokeh-2.4.3.min.js:519:9879)
    at O.after_layout (bokeh-2.4.3.min.js:519:9706)
    at O.compute_layout (bokeh-2.4.3.min.js:496:3047)
2bokeh-2.4.3.min.js:230 
        
       Uncaught (in promise) Error: invalid bbox {left: NaN, top: 300.6363525390625, right: NaN, bottom: 312.6363525390625}
    at new o (bokeh-2.4.3.min.js:230:1190)
    at u.bbox (bokeh-2.4.3.min.js:285:773)
    at bokeh-2.4.3.min.js:293:5126
    at Array.map (<anonymous>)
    at a._draw_oriented_labels (bokeh-2.4.3.min.js:293:5116)
    at a._draw_major_labels (bokeh-2.4.3.min.js:293:2964)
    at a._render (bokeh-2.4.3.min.js:293:1544)
    at a.render (bokeh-2.4.3.min.js:206:1562)
    at O._paint_levels (bokeh-2.4.3.min.js:519:11560)
    at O._actual_paint (bokeh-2.4.3.min.js:519:10976)
```

**Comment by wangvsa** [comment]
Hi Rob, can you let me know if the issue still exists for the latest version 0.4.5?

**Comment by roblatham00** [comment]
I still get the little bokeh icon (instead of a plot) for those two graphs.  The console output looks mostly the same, except no longer complaining about "this.text.split is not a function"
```
[bokeh] document idle at 11 ms
bokeh-2.4.3.min.js:165 [bokeh] document idle at 10 ms
bokeh-2.4.3.min.js:165 [bokeh] document idle at 7 ms
bokeh-2.4.3.min.js:165 [bokeh] document idle at 16 ms
bokeh-2.4.3.min.js:165 [bokeh] document idle at 13 ms
3bokeh-2.4.3.min.js:521 
        
       [bokeh] could not set initial ranges
compute_initial @ bokeh-2.4.3.min.js:521
bokeh-2.4.3.min.js:165 [bokeh] document idle at 7 ms
bokeh-2.4.3.min.js:165 [bokeh] document idle at 3 ms
bokeh-2.4.3.min.js:165 [bokeh] document idle at 1 ms
bokeh-2.4.3.min.js:228 
        
       [bokeh] could not determine minimum data value for log axis, DataRange1d using value 0.1
_compute_range @ bokeh-2.4.3.min.js:228
bokeh-2.4.3.min.js:228 
        
       [bokeh] could not determine maximum data value for log axis, DataRange1d using value 10
_compute_range @ bokeh-2.4.3.min.js:228
bokeh-2.4.3.min.js:228 
        
       [bokeh] could not determine minimum data value for log axis, DataRange1d using value 0.1
_compute_range @ bokeh-2.4.3.min.js:228
bokeh-2.4.3.min.js:228 
        
       [bokeh] could not determine maximum data value for log axis, DataRange1d using value 10
_compute_range @ bokeh-2.4.3.min.js:228
2bokeh-2.4.3.min.js:230 
        
       Uncaught (in promise) Error: invalid bbox {left: NaN, top: 300.6363525390625, right: NaN, bottom: 312.6363525390625}
    at new o (bokeh-2.4.3.min.js:230:1190)
    at u.bbox (bokeh-2.4.3.min.js:285:773)
    at bokeh-2.4.3.min.js:293:5126
    at Array.map (<anonymous>)
    at a._draw_oriented_labels (bokeh-2.4.3.min.js:293:5116)
    at a._draw_major_labels (bokeh-2.4.3.min.js:293:2964)
    at a._render (bokeh-2.4.3.min.js:293:1544)
    at a.render (bokeh-2.4.3.min.js:206:1562)
    at O._paint_levels (bokeh-2.4.3.min.js:519:11560)
    at O._actual_paint (bokeh-2.4.3.min.js:519:10976)
```

**Comment by wangvsa** [comment]
Could you send me your traces or probably just the command you used to run IOR?

**Comment by wangvsa** [comment]
The issue is that there are no POSIX I/O calls in your traces. I think it has something to do with the "extern inline".
Because without "extern inline", the same ior run gives "correct" traces.

BTW, you can use recorder2text to generate records in plain text, e.g., `path/to/recorder2text ./recorder-20220912/LAPTOP-QV97NQLH-(null)-ior-2607-100206.721/`

For example, here are some of your records from rank 2:
```
0.0027280 0.0027311 MPI_File_read_at 0 1 ( 0-3 2000 %p 1000 MPI_BYTE [0_1275068673] )         
0.0027339 0.0027890 MPI_File_close 0 1 ( 0-3 )
0.0027930 0.0030040 MPI_File_open 0 1 ( 0-2 /home/robl/work/Recorder/build/testFile 2 %p 0-4 )
0.0028800 0.0028800 umask 1 0 ( 18 )
```
There should be POSIX calls like pread, close, open after the corresponding MPI-IO calls. But we didn't see them. Can you try "extern" instead of "extern inline" to see if that also solves the compile error?

**Comment by roblatham00** [comment]
ok, well we are back to my original build errors, which we can chalk up to my oddball environment.  I will close this now, unless I can reproduce it in a more typical environment.
